### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by callzhang** [sbonami/PFIncrementalStore#36]
Can you add a brief documentation about how to use this framework?

**Comment by sbonami** [comment]
Along with [proper examples](https://github.com/sbonami/PFIncrementalStore/pull/5), better documentation is on my to-do list. I'll see what I can do by way of a readme update and I'll post back here.

**Comment by callzhang** [comment]
Thank you. Please keep me posted.
Also, I would like to have your option about AFIncrementalStore. Do you think it is in a usable state?

**Comment by sbonami** [comment]
Check out the github site I threw together with installation/usage instructions: http://sbonami.github.io/PFIncrementalStore/

Also, I'd definitely suggest AFIncrementalStore as a proper NSIncrementalStore subclass for talking with REST apis, however I can't comment on whether it's usable for any particular use case. I've used it in the past and been very happy with it, however I have seen a complaint or two about it in certain instances.

**Comment by yzoldan** [comment]
Hi I'm really interested in what you are doing. I read your github site but I couldn't figure out how to use PFIncrementalStore. I don't mean how to install it but how to actually use the PFObjects or Entities inside my project. Are you planning on providing usage examples? That would be great if you do!
Thanks in advance!

**Comment by Alydyn** [comment]
@yzoldan you really shouldn't have to use PFObjects.  Since this is an NSIncrementalStore implementation you are really working with Core Data.  PFIS works on connecting to Parse.com and persisting there.
I suggest googling NSIncrementalStore; there are a lot of great articles that document what it does, including one on NSHipster (http://nshipster.com/nsincrementalstore/) and one by Drew Crawford (http://sealedabstract.com/code/nsincrementalstore-the-future-of-web-services-in-ios-mac-os-x/)

EDIT: I should really point out that, due to the rough edges of the Parse.com non-standard REST API, this framework is necessary, rather than a "stock" implementation like AFIncrementalStore.  See (http://blog.palominolabs.com/2014/03/20/parse-gotchas/?utm_campaign=iOS_Dev_Weekly_Issue_139&utm_medium=email&utm_source=iOS%2BDev%2BWeekly) for more about the rough edges of Parse.com.

**Comment by yzoldan** [comment]
@Alydyn Sorry for the noob question :). I will definitely check those links, thanks!

**Comment by Alydyn** [comment]
@yzoldan no worries!  IncrementalStore is a lot to wrap your head around.  Happy to help in any way I can.
