### ISSUE TITLE
Podfile.lock missing

### ISSUE THREAD

**Issue by callzhang** [sbonami/PFIncrementalStore#50]
When I run, xcode prompt:
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

Please check that you included Podfile.lock or let me know how to run this example.

**Comment by hokster7** [comment]
Have you followed the instructions in the error?

You must have [Cocoapods](http://cocoapods.org) installed (so that you can get the `pod` command) and then you should execute `pod install` in the directory you checked out PFIncrementalStore.

Cocoapods is a dependency manager. `Podfile.lock` is a file that's generated by Cocoapods that records the exact versions of dependencies that the project uses.

Good point though — this file should have been checked into source control, so @sbonami it is strange that it's not available. 

EDIT: Added more info

**Comment by callzhang** [comment]
I do have Pod installed. I can run Pod Install on the example directory, but not on the main directory, where No 'Podfile' is found. Therefore, I can open and run the workspace in each individual example folder, but not on the root folder. It looks strange to me for this kind of file organization tho.

Also, in the example, I suggest to add a 'add record' button, because the table is empty and there is no way to add a record at beginning.

**Comment by sbonami** [comment]
@callzhang The organization is based on [AFIncrementalStore's](https://github.com/AFNetworking/AFIncrementalStore) repo. Since this is a library and not an app, it does not contain a `Podfile` or `Podfile.lock`. Any app, like [Test](https://github.com/sbonami/PFIncrementalStore/tree/master/Tests) or the [Examples](https://github.com/sbonami/PFIncrementalStore/tree/master/Examples), require this library thus they require a Podfile.

@fatuhoku: In reference to not including the `Podfile.lock`, I originally included it but decided to remove it since [AFNetworking chose to](https://github.com/AFNetworking/AFNetworking/blob/master/.gitignore#L20). This thread is a good indication that I may need to re-think that thought process.
